# Generated by Django 5.1.1 on 2024-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Кошелёк'),
        ),
    ]
